// AUTO-GENERATED list of the legacy Anu Telugu fonts self-hosted under
// apps/admin/public/anu-fonts/. Each entry's `value` is the @font-face
// family name (the .ttf basename) declared in /anu-fonts/anu-fonts.css, so a
// chosen font resolves once that stylesheet is loaded. These are byte-encoded
// display faces - the server PDF render maps Unicode->Anu bytes (see
// ./anu-encoder + ./anu-font-face); the picker just exposes them for selection.
//
// To regenerate after adding/removing .ttf files:
//   node -e '...'  (see chat / scripts) - do not hand-edit individual rows.
import type { TeluguFont } from "./telugu-fonts";

export const ANU_FONTS: TeluguFont[] = [
  { label: "Aaradhana", value: "'Aaradhana'", google: null, anu: true },
  { label: "Abhilasha", value: "'Abhilasha'", google: null, anu: true },
  { label: "Ajantha", value: "'Ajantha'", google: null, anu: true },
  { label: "Akshara", value: "'Akshara'", google: null, anu: true },
  { label: "Amrutha", value: "'Amrutha'", google: null, anu: true },
  { label: "Anek Telugu Bold", value: "'Anek-Telugu-Bold'", google: null, anu: true },
  { label: "Anek Telugu ExtraBold", value: "'Anek-Telugu-ExtraBold'", google: null, anu: true },
  { label: "Anek Telugu ExtraLight", value: "'Anek-Telugu-ExtraLight'", google: null, anu: true },
  { label: "Anek Telugu Light", value: "'Anek-Telugu-Light'", google: null, anu: true },
  { label: "Anek Telugu Medium", value: "'Anek-Telugu-Medium'", google: null, anu: true },
  { label: "Anek Telugu Regular", value: "'Anek-Telugu-Regular'", google: null, anu: true },
  { label: "Anek Telugu SemiBold", value: "'Anek-Telugu-SemiBold'", google: null, anu: true },
  { label: "Anek Telugu Thin", value: "'Anek-Telugu-Thin'", google: null, anu: true },
  { label: "Anjali", value: "'Anjali'", google: null, anu: true },
  { label: "Anu Subhalekha Two", value: "'Anu-Subhalekha-Two'", google: null, anu: true },
  { label: "Anupama Bold", value: "'Anupama-Bold'", google: null, anu: true },
  { label: "Anupama Ext Bold", value: "'Anupama-Ext-Bold'", google: null, anu: true },
  { label: "Anupama Medium", value: "'Anupama-Medium'", google: null, anu: true },
  { label: "Anupama Thin", value: "'Anupama-Thin'", google: null, anu: true },
  { label: "Anusha", value: "'Anusha'", google: null, anu: true },
  { label: "Anuso", value: "'Anuso'", google: null, anu: true },
  { label: "Apoorva", value: "'Apoorva'", google: null, anu: true },
  { label: "Ashwini", value: "'Ashwini'", google: null, anu: true },
  { label: "Avanthi", value: "'Avanthi'", google: null, anu: true },
  { label: "Bapu Bold", value: "'Bapu-Bold'", google: null, anu: true },
  { label: "Bapu Brush", value: "'Bapu-Brush'", google: null, anu: true },
  { label: "Bapu Script", value: "'Bapu-Script'", google: null, anu: true },
  { label: "Bharghava", value: "'Bharghava'", google: null, anu: true },
  { label: "Bhavya", value: "'Bhavya'", google: null, anu: true },
  { label: "Brahma", value: "'Brahma'", google: null, anu: true },
  { label: "Brahma Script", value: "'Brahma-Script'", google: null, anu: true },
  { label: "Chandra Script", value: "'Chandra-Script'", google: null, anu: true },
  { label: "Charitha", value: "'Charitha'", google: null, anu: true },
  { label: "Deepika", value: "'Deepika'", google: null, anu: true },
  { label: "Dharani", value: "'Dharani'", google: null, anu: true },
  { label: "Dingbits Eight", value: "'Dingbits-Eight'", google: null, anu: true },
  { label: "Dingbits Eleven", value: "'Dingbits-Eleven'", google: null, anu: true },
  { label: "Dingbits Five", value: "'Dingbits-Five'", google: null, anu: true },
  { label: "Dingbits Four", value: "'Dingbits-Four'", google: null, anu: true },
  { label: "Dingbits Nine", value: "'Dingbits-Nine'", google: null, anu: true },
  { label: "Dingbits One", value: "'Dingbits-One'", google: null, anu: true },
  { label: "Dingbits Seven", value: "'Dingbits-Seven'", google: null, anu: true },
  { label: "Dingbits Six", value: "'Dingbits-Six'", google: null, anu: true },
  { label: "Dingbits Ten", value: "'Dingbits-Ten'", google: null, anu: true },
  { label: "Dingbits Thirteen", value: "'Dingbits-Thirteen'", google: null, anu: true },
  { label: "Dingbits Three", value: "'Dingbits-Three'", google: null, anu: true },
  { label: "Dingbits Twelve", value: "'Dingbits-Twelve'", google: null, anu: true },
  { label: "Dingbits Two", value: "'Dingbits-Two'", google: null, anu: true },
  { label: "Geetha", value: "'Geetha'", google: null, anu: true },
  { label: "Gowthami Black", value: "'Gowthami-Black'", google: null, anu: true },
  { label: "Gowthami Bold", value: "'Gowthami-Bold'", google: null, anu: true },
  { label: "Gowthami Ext Bold", value: "'Gowthami-Ext-Bold'", google: null, anu: true },
  { label: "Gowthami Medium", value: "'Gowthami-Medium'", google: null, anu: true },
  { label: "Gowthami Narrow", value: "'Gowthami-Narrow'", google: null, anu: true },
  { label: "Gowthami Thin", value: "'Gowthami-Thin'", google: null, anu: true },
  { label: "Harsha", value: "'Harsha'", google: null, anu: true },
  { label: "Hiranya", value: "'Hiranya'", google: null, anu: true },
  { label: "Jyothi", value: "'Jyothi'", google: null, anu: true },
  { label: "Kalaanjali", value: "'Kalaanjali'", google: null, anu: true },
  { label: "Keerthi Font", value: "'Keerthi-Font'", google: null, anu: true },
  { label: "Kranthi", value: "'Kranthi'", google: null, anu: true },
  { label: "Kusuma", value: "'Kusuma'", google: null, anu: true },
  { label: "Maanasa", value: "'Maanasa'", google: null, anu: true },
  { label: "Madhubala", value: "'Madhubala'", google: null, anu: true },
  { label: "Meena Script", value: "'Meena-Script'", google: null, anu: true },
  { label: "Mohini", value: "'Mohini'", google: null, anu: true },
  { label: "Natyamayuri", value: "'Natyamayuri'", google: null, anu: true },
  { label: "Neelima", value: "'Neelima'", google: null, anu: true },
  { label: "Padmini", value: "'Padmini'", google: null, anu: true },
  { label: "Pallavi Bold", value: "'Pallavi-Bold'", google: null, anu: true },
  { label: "Pallavi Medium", value: "'Pallavi-Medium'", google: null, anu: true },
  { label: "Pallavi Thin", value: "'Pallavi-Thin'", google: null, anu: true },
  { label: "Prabhava", value: "'Prabhava'", google: null, anu: true },
  { label: "Pragathi", value: "'Pragathi'", google: null, anu: true },
  { label: "Pragathi Italic", value: "'Pragathi-Italic'", google: null, anu: true },
  { label: "Pragathi Narrow", value: "'Pragathi-Narrow'", google: null, anu: true },
  { label: "Pragathi Special", value: "'Pragathi-Special'", google: null, anu: true },
  { label: "Praveena", value: "'Praveena'", google: null, anu: true },
  { label: "Preethi", value: "'Preethi'", google: null, anu: true },
  { label: "Pridhvi", value: "'Pridhvi'", google: null, anu: true },
  { label: "Priyaanka", value: "'Priyaanka'", google: null, anu: true },
  { label: "Priyaanka Bold", value: "'Priyaanka-Bold'", google: null, anu: true },
  { label: "Rachana", value: "'Rachana'", google: null, anu: true },
  { label: "Rachana Bold", value: "'Rachana-Bold'", google: null, anu: true },
  { label: "Ramana Brush", value: "'Ramana-Brush'", google: null, anu: true },
  { label: "Ramana Script", value: "'Ramana-Script'", google: null, anu: true },
  { label: "Ramana Script Med", value: "'Ramana-Script-Med'", google: null, anu: true },
  { label: "Ravali", value: "'Ravali'", google: null, anu: true },
  { label: "Reshma", value: "'Reshma'", google: null, anu: true },
  { label: "Rohini", value: "'Rohini'", google: null, anu: true },
  { label: "Saagari", value: "'Saagari'", google: null, anu: true },
  { label: "Sanghavi", value: "'Sanghavi'", google: null, anu: true },
  { label: "Sowmya", value: "'Sowmya'", google: null, anu: true },
  { label: "Sravya", value: "'Sravya'", google: null, anu: true },
  { label: "Srujana", value: "'Srujana'", google: null, anu: true },
  { label: "Subhadra", value: "'Subhadra'", google: null, anu: true },
  { label: "Suchithra", value: "'Suchithra'", google: null, anu: true },
  { label: "Sujatha", value: "'Sujatha'", google: null, anu: true },
  { label: "Suneetha", value: "'Suneetha'", google: null, anu: true },
  { label: "Supriya", value: "'Supriya'", google: null, anu: true },
  { label: "Tejafont", value: "'Tejafont'", google: null, anu: true },
  { label: "Telun Bold", value: "'Telun-Bold'", google: null, anu: true },
  { label: "Telun Thin", value: "'Telun-Thin'", google: null, anu: true },
  { label: "Thripura", value: "'Thripura'", google: null, anu: true },
  { label: "Udayam", value: "'Udayam'", google: null, anu: true },
  { label: "Vaibhav", value: "'Vaibhav'", google: null, anu: true },
  { label: "Vasantha", value: "'Vasantha'", google: null, anu: true },
  { label: "Vasundhara", value: "'Vasundhara'", google: null, anu: true },
  { label: "Veenaa", value: "'Veenaa'", google: null, anu: true },
  { label: "Vikaas", value: "'Vikaas'", google: null, anu: true },
];
